/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as MarketsMarketIdRouteImport } from './routes/markets.$marketId'
import { Route as MfaVerifyRouteImport } from './routes/mfa.verify'
import { Route as PortfolioExportsRouteImport } from './routes/portfolio.exports'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as ApiRealtimePortfolioRouteImport } from './routes/api.realtime.portfolio'
import { Route as PortfolioHistoryFillsRouteImport } from './routes/portfolio.history.fills'
import { Route as PortfolioHistoryOrdersRouteImport } from './routes/portfolio.history.orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/markets/$marketId',
  path: '/markets/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaVerifyRoute = MfaVerifyRouteImport.update({
  id: '/mfa/verify',
  path: '/mfa/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioExportsRoute = PortfolioExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => PortfolioRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimePortfolioRoute = ApiRealtimePortfolioRouteImport.update({
  id: '/api/realtime/portfolio',
  path: '/api/realtime/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioHistoryFillsRoute = PortfolioHistoryFillsRouteImport.update({
  id: '/history/fills',
  path: '/history/fills',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioHistoryOrdersRoute = PortfolioHistoryOrdersRouteImport.update({
  id: '/history/orders',
  path: '/history/orders',
  getParentRoute: () => PortfolioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/portfolio/exports': typeof PortfolioExportsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/api/realtime/portfolio': typeof ApiRealtimePortfolioRoute
  '/portfolio/history/fills': typeof PortfolioHistoryFillsRoute
  '/portfolio/history/orders': typeof PortfolioHistoryOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/portfolio/exports': typeof PortfolioExportsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/api/realtime/portfolio': typeof ApiRealtimePortfolioRoute
  '/portfolio/history/fills': typeof PortfolioHistoryFillsRoute
  '/portfolio/history/orders': typeof PortfolioHistoryOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/portfolio/exports': typeof PortfolioExportsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/api/realtime/portfolio': typeof ApiRealtimePortfolioRoute
  '/portfolio/history/fills': typeof PortfolioHistoryFillsRoute
  '/portfolio/history/orders': typeof PortfolioHistoryOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portfolio'
    | '/register'
    | '/verify-email'
    | '/wallet'
    | '/markets/$marketId'
    | '/mfa/verify'
    | '/portfolio/exports'
    | '/settings/security'
    | '/api/realtime/portfolio'
    | '/portfolio/history/fills'
    | '/portfolio/history/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portfolio'
    | '/register'
    | '/verify-email'
    | '/wallet'
    | '/markets/$marketId'
    | '/mfa/verify'
    | '/portfolio/exports'
    | '/settings/security'
    | '/api/realtime/portfolio'
    | '/portfolio/history/fills'
    | '/portfolio/history/orders'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portfolio'
    | '/register'
    | '/verify-email'
    | '/wallet'
    | '/markets/$marketId'
    | '/mfa/verify'
    | '/portfolio/exports'
    | '/settings/security'
    | '/api/realtime/portfolio'
    | '/portfolio/history/fills'
    | '/portfolio/history/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WalletRoute: typeof WalletRoute
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
  MfaVerifyRoute: typeof MfaVerifyRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  ApiRealtimePortfolioRoute: typeof ApiRealtimePortfolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/markets/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/verify': {
      id: '/mfa/verify'
      path: '/mfa/verify'
      fullPath: '/mfa/verify'
      preLoaderRoute: typeof MfaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/exports': {
      id: '/portfolio/exports'
      path: '/exports'
      fullPath: '/portfolio/exports'
      preLoaderRoute: typeof PortfolioExportsRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime/portfolio': {
      id: '/api/realtime/portfolio'
      path: '/api/realtime/portfolio'
      fullPath: '/api/realtime/portfolio'
      preLoaderRoute: typeof ApiRealtimePortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/history/fills': {
      id: '/portfolio/history/fills'
      path: '/history/fills'
      fullPath: '/portfolio/history/fills'
      preLoaderRoute: typeof PortfolioHistoryFillsRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/history/orders': {
      id: '/portfolio/history/orders'
      path: '/history/orders'
      fullPath: '/portfolio/history/orders'
      preLoaderRoute: typeof PortfolioHistoryOrdersRouteImport
      parentRoute: typeof PortfolioRoute
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioExportsRoute: typeof PortfolioExportsRoute
  PortfolioHistoryFillsRoute: typeof PortfolioHistoryFillsRoute
  PortfolioHistoryOrdersRoute: typeof PortfolioHistoryOrdersRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioExportsRoute: PortfolioExportsRoute,
  PortfolioHistoryFillsRoute: PortfolioHistoryFillsRoute,
  PortfolioHistoryOrdersRoute: PortfolioHistoryOrdersRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WalletRoute: WalletRoute,
  MarketsMarketIdRoute: MarketsMarketIdRoute,
  MfaVerifyRoute: MfaVerifyRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  ApiRealtimePortfolioRoute: ApiRealtimePortfolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
